### PR TITLE
Hicexplorer wrappers

### PR DESCRIPTION
**Pull request by lldelisle**
Hi,
This should solve the hicPlotAverageRegions issue.

### CODE REVIEW

**Comment by joachimwolff** [comment]
Hi Lucille,

Thanks a lot! I didn’t know you have to define ftype for the input files in a test case too, for all other test cases it is not necessary. 

Do you have maybe an idea what is wrong with hicFindTads? If I run it on my computer the two test cases are executed successfully, but on travis it is just one test case with a really weird error message.

Best,

Joachim

**Comment by lldelisle** [comment]
>  I didn’t know you have to define ftype for the input files in a test case too.

Yes, if the datatype cannot be guessed, you need to specify it.
> Do you have maybe an idea what is wrong with hicFindTads?

No, this is super weird. I tried: `planemo t --galaxy_branch release_19.09` locally and it also passed the 2 tests.
Even more strange, I created a branch with only this tool and travis worked... I am now trying to put back more tools to see how is it working.
If I do not manage, I think we can ask to the iuc on gitter...

**Comment by joachimwolff** [comment]
The tool_id was wrong... Stupid copy & paste errors :) Thanks so much for debugging this, two people here in the office missed that one!

**Comment by lldelisle** [comment]
You're welcome. At least, this allow me to spot 2 errors in the hicPlotAverageRegions tool.

**Pull request merged**
